doctrine:
    dbal:
        connections:
            shop:
                #url: '%mysql.shop.url%'
                dbname: '%mysql.shop.dbname%'
                host:  '%mysql.shop.url%'
                port: '%mysql.shop.port%'
                user: '%mysql.shop.username%'
                password: '%mysql.shop.password%'
                server_version: '8.0'
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: shop
                mappings:
                    Shop:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
